# name: Docker Image CI

# on:
#   push:
#     branches: [ master, develop ]
# #   pull_request:
# #     branches: [ master ]
# #   release:
# #     # Only use the types keyword to narrow down the activity types that will trigger your workflow.
# #     types: [published, created, edited]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Build and push Docker images
#       uses: docker/build-push-action@v1
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
#         repository: nikhilgorantla/1-trash
#         tag_with_ref: true
# #         tag_with_sha: true

#     - name: Create Release Folder
#       run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./release
#     - name: Switch to Release Folder
#       run: |
#         cd release
#         ls -la
#     - name: Bump version and push tag
#       uses: anothrNick/github-tag-action@master
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         REPO_OWNER: nikhil
